stages:
  - deploy

stage:
  stage: deploy
  only:
    refs:
      - develop
    variables:
      - $CI_SERVER_HOST == "gitlab.agiqon.de"
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=develop "https://gitlab.agiqon.de/api/v4/projects/522/trigger/pipeline"

prod:
  stage: deploy
  only:
    refs:
      - main
    variables:
      - $CI_SERVER_HOST == "gitlab.agiqon.de"
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=main "https://gitlab.agiqon.de/api/v4/projects/522/trigger/pipeline"
